### PR TITLE
#4 Layout Component

### PR DESCRIPTION
**Pull request by Kathuria**
Issue #4: Create a layout component

### CODE REVIEW

**Comment by Kathuria** [comment]
@smilegupta: Changes are done for layout but haven't created separate branch with issue-4 because develop branch is not even with master, home component files was missing. Thus updated this branch with required files.

Please review changes, if required any more changes related to layout or need to commit in separate branch - Please update me

**Review by smilegupta — APPROVED** [review]
Greetings from Build With Girlscript Bangalore😃

Dear participant,

We have gone through your pull request made for the issue 4<issue number>
 
Congratulations🎊 🎉 on getting your pull request successfully merged into our application **Build with GSBlr-Raahat.** 

We will soon be distributing your valuable badge(s)🥇🥈🥉🎖️ corresponding to the pull requests that are merged. Please fill the [participation form](https://tinyurl.com/buildwithgsblr) 📃 to receive your badges, if not already done.

Also, [RSVP here](https://tinyurl.com/gsblr-hacktoberfest2020) , if you haven't yet,  to get a chance to win a limited-edition Hacktoberfest 👕 T-shirt or a 🎍plant.

Learning is a never-ending process. 📈  We will be coming up with *new issues*, stay tuned. Meanwhile you can also check out our other [Code with GirlScript Bangalore Repository](https://github.com/girlscript-blr/code-with-girlscript-bangalore) to try some problem solving and earn exciting badges.

Thanks for your contribution! Happy coding😃

**Comment by girlscript-blr** [comment]
Hi @Kathuria 

Please fill the [participation form](https://tinyurl.com/buildwithgsblr) 📃 to receive your badges.

Thanks

**Comment by Kathuria** [comment]
@girlscript-blr Done.

Thanks Team

**Pull request merged**
