### PR TITLE
Issue 8

### PR DESCRIPTION
**Pull request by rohit-kadam-hub**
As per your requirement, I have added the modal component of issue-8.

### CODE REVIEW

**Review by smilegupta — COMMENTED** [review]
Dear participant,

We have gone through your pull request made for the issue 8<issue number>
 
Congratulations🎊 🎉 on getting your pull request successfully merged into our application **Build with GSBlr-Raahat.** 

We will soon be distributing your valuable badge(s)🥇🥈🥉🎖️ corresponding to the pull requests that are merged. Please fill the [participation form](https://tinyurl.com/buildwithgsblr) 📃 to receive your badges, if not already done.

Also, [RSVP here](https://tinyurl.com/gsblr-hacktoberfest2020) , if you haven't yet,  to get a chance to win a limited-edition Hacktoberfest 👕 T-shirt or a 🎍plant.

Learning is a never-ending process. 📈  We will be coming up with *new issues*, stay tuned. Meanwhile you can also check out our other [Code with GirlScript Bangalore Repository](https://github.com/girlscript-blr/code-with-girlscript-bangalore) to try some problem solving and earn exciting badges.

Thanks for your contribution! Happy coding😃

**Comment by smilegupta** [comment]
Good one!

**Review by smilegupta — APPROVED** [review]
Dear participant,

We have gone through your pull request made for the issue #

Congratulations🎊 🎉 on getting your pull request successfully merged into our application Build with GSBlr-Raahat.

We will soon be distributing your valuable badge(s)🥇🥈🥉🎖️ corresponding to the pull requests that are merged. Please fill the participation form 📃 to receive your badges, if not already done.

Also, RSVP here here, if you haven't yet, to get a chance to win a limited-edition Hacktoberfest 👕 T-shirt or a 🎍plant.

Learning is a never-ending process. 📈 We will be coming up with new issues, stay tuned. Meanwhile you can also check out our other Code with GirlScript Bangalore Repository to try some problem solving and earn exciting badges.

Thanks for your contribution! Happy coding😃

**Comment by rohit-kadam-hub** [comment]
Thanks.!

**Pull request merged**
