### PR TITLE
Develop Footer Component #3

### PR DESCRIPTION
**Pull request by karshil2309**
Hey, there I tried to make footer component. I want some help in aligning the components. After that pls let me know how should be the view in  mobile view.

### CODE REVIEW

**Comment by smilegupta** [comment]
@karshil2309 can u add a screenshots of your code! i am not able to view anything via vercel!!

**Review by smilegupta — CHANGES_REQUESTED** [review]
Please refactor your code and plus! the files which are not at all relevant to the project! should not be part of the code base! Plus if you made the footer component! separately! kindly also call them in the main app file! so that we all may be able to see as in person!

**Review by Kathuria — CHANGES_REQUESTED** [review]
As mentioned and reviewed by maintainer, I would like to add
1) .gitignore already added in project where package.json is placed, like project/.gitignore - You can update that for those files you want do not push like .idea in your case.
2) Ignore all .idea or .vscode files - never commit
3) Why bulma version bump, do you need it? If not, let maintainer handle package versions
4) In CSS, remove empty class for media if you are not handling
But you should consider adding css for different viewports and consider different browsers as well. Check css-tricks or similar website.
5) In react, you have to write a component not html file, check components/header is source - Just imitate that and you are good to go.

**Comment by karshil2309** [comment]
> Please refactor your code and plus! the files which are not at all relevant to the project! should not be part of the code base! Plus if you made the footer component! separately! kindly also call them in the main app file! so that we all may be able to see as in person!

@smilegupta Okay will do that

**Comment by karshil2309** [comment]
> As mentioned and reviewed by maintainer, I would like to add
> 
> 1. .gitignore already added in project where package.json is placed, like project/.gitignore - You can update that for those files you want do not push like .idea in your case.
> 2. Ignore all .idea or .vscode files - never commit
> 3. Why bulma version bump, do you need it? If not, let maintainer handle package versions
> 4. In CSS, remove empty class for media if you are not handling
>    But you should consider adding css for different viewports and consider different browsers as well. Check css-tricks or similar website.
> 5. In react, you have to write a component not html file, check components/header is source - Just imitate that and you are good to go.

@Kathuria Sure, will do that pls give some time. Thank you!

**Comment by karshil2309** [comment]
Screenshot (4)
Updated Screenshot

**Pull request closed without merging**
