### PR TITLE
Issue #7 create surveyresult for home page

### PR DESCRIPTION
**Pull request by Harshitha-sa**
Created Survey Result page!, Please Check!
#7 
image

### CODE REVIEW

**Comment by Harshitha-sa** [comment]
Preview at: https://build-with-gsblr-raahat-git-master.girlscript-blr.vercel.app/surveyResult

**Comment by Swatijaiswal-Tech** [comment]
@Harshitha-sa, I would like to appreciate your effort  but there is responsiveness issue in  
Screenshot 2020-10-10 at 9 22 35 PM
Screenshot 2020-10-10 at 9 22 14 PM

mobile view please do check one more time and also check there should not be any console error .

hints :  -
1.class should be  classname 
2.css issue you can write your own surveyresult.css 
keep coding  ....

**Comment by savioursBlr** [comment]
Okay ill look into it..Thankyou!

**Comment by Harshitha-sa** [comment]
Okay, i'll look into it!,Thankyou

**Comment by Harshitha-sa** [comment]
I have made the changes: https://build-with-gsblr-raahat-kdpdidocc.vercel.app/surveyResult

**Comment by smilegupta** [comment]
@Harshitha-sa  can you do me a thing, can u change the target branch to develop and resolve the merge conflicts and may sent a fresh pr please

**Comment by Harshitha-sa** [comment]
Okay I will do that 👍

**Comment by smilegupta** [comment]
@Harshitha-sa  your target branch was still master! I had changed the base to develop! can u resolve the Merge conflics please

**Review by smilegupta — APPROVED** [review]

**Comment by smilegupta** [comment]
@Harshitha-sa  it would be really great, if you may resolve the Merge Conflicts, and update your PR so that i will be able to merge the same to the develop branch

**Comment by smilegupta** [comment]
Greetings from Build With Girlscript Bangalore😃

Dear participant,

We have gone through your pull request made for the issue #17

Congratulations🎊 🎉 on getting your pull request successfully merged into our application Build with GSBlr-Raahat.

We will soon be distributing your valuable badge(s)🥇🥈🥉🎖️ corresponding to the pull requests that are merged. Please fill the participation form 📃 to receive your badges, if not already done.

Also, RSVP here here, if you haven't yet, to get a chance to win a limited-edition Hacktoberfest 👕 T-shirt or a 🎍plant.

Learning is a never-ending process. 📈 We will be coming up with new issues, stay tuned. Meanwhile you can also check out our other Code with GirlScript Bangalore Repository to try some problem solving and earn exciting badges.

Thanks for your contribution! Happy coding😃

**Pull request merged**
